name: Docker Image CI

on:
  create:
    tags: 
      - '*'
  push:
    branches: [ mvn ]

jobs:

  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    -
        name: Login to DockerHub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKER_LOGIN }}
          password: ${{ secrets.DOCKER_PASSWORD }}
    -
       name: Build
       run: |
          docker build -t getcarrier/gatling_maven_runner:latest-3.7 .
    -
       name: Push
       run: |
         docker push getcarrier/gatling_maven_runner:latest-3.7
